name: Monthly Content Refresh

on:
  schedule:
    # 1st of every month at 2 AM UTC
    - cron: '0 2 1 * *'
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  refresh-content:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
        
      - name: Run content refresh
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_ANYCRAWL_API_KEY: ${{ secrets.VITE_ANYCRAWL_API_KEY }}
        run: node scripts/refresh-content.js